title: Mamesa El
logo: /Images/half_body_photo.jpg
show_download: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

github:
  zip_url: http://example.com/download.zip
  another_url: another value

LinkedIn:
  url: https://www.linkedin.com/in/mamesael/